### ISSUE TITLE
add a GetAllAwsAccounts method

### ISSUE THREAD

**Issue by ryno75** [nextgenhealthcare/cloudhealth-sdk-go#4]
Would be nice to have a `GetAllAwsAccounts` method for retrieving a slice of AwsAccount.  Obviously not something needed for Terraform but for an SDK in general this is handy.  I've actually written the code for this (so I can batch delete a bunch of auto-imported from the CUR duplicate AWS accounts).  PR coming shortly.

**Comment by brandonstevens** [comment]
Really appreciate the contribution!
